/**
 * 推荐车源模板
 * @param sourceFirst {function} 首次渲染10条
 * @param onscroll {function} 滚动事件
 */
var sourceFirst=function(){
    var HTML=[
        '{@if OBJAPP === true}',
            '{@each data.rows as it, i}',
                '<li class="recommend">',
                '{@if it.sellOut == true}',
                    '<a>',
                '{@else}',
                    '<a href="cybapp://car/id/${it.id}">',
                '{@/if}',
                '<div class="recommendImgBox">',
                    '<img src="" data-src="${it.carImg}" class="recommendImg">',
                '{@if it.sellOut == true}',
                    '<img src="img/sell_outsmall.png" class="sellOutSmall"/>',
                '{@/if}',
                '</div>',
                    '<div class="recommendText">',
                        '<div class="recommendCarName strongText">${it.carName}</div>',
                        '<div class="fontColor fontSize-14 smallOut">',
                            '<span>外观/内饰:</span>',
                            '<span class="marginLeft-5">${it.carFace}/${it.carInterior}</span>',
                        '</div>',
                        '<div class="fontColor fontSize-14 smallPrice">',
                        '{@if it.carSale == 0}',
                            '<span class="recommendCarSale">电议</span>',
                        '{@else}',
                            '<span class="recommendCarSale">￥${it.carSale}万</span>',
                        '{@/if}',
                '{@if it.carPrice != null && it.carPrice !=0}',
                    '<span class="marginLeft-5 recommendCarPrice">指导价:${it.carPrice}万</span>',
                '{@/if}',
                '</div>',
                        '</div>',
                    '</a>',
                '</li>',
            '{@/each}',
        '{@/if}',
        '{@if OBJAPP === false}',
            '{@if ImgObj === 0}',
                '{@each data.rows as it, i}',
                    '<li class="recommend">',
                    '{@if it.sellOut == true}',
                        '<a>',
                    '{@else}',
                        '<a href="cybapp://car/id/${it.id}">',
                    '{@/if}',
                    '<div class="recommendImgBox">',
                        '<img src="" data-src="${it.carImg}" class="recommendImg">',
                    '{@if it.sellOut == true}',
                        '<img src="img/sell_outsmall.png" class="sellOutSmall"/>',
                    '{@/if}',
                    '</div>',
                        '<div class="recommendText">',
                            '<div class="recommendCarName strongText">${it.carName}</div>',
                            '<div class="fontColor fontSize-14 smallOut">',
                                '<span>外观/内饰:</span>',
                                '<span class="marginLeft-5">${it.carFace}/${it.carInterior}</span>',
                            '</div>',
                            '<div class="fontColor fontSize-14 smallPrice">',
                        '{@if it.carSale == 0}',
                            '<span class="recommendCarSale">电议</span>',
                        '{@else}',
                            '<span class="recommendCarSale">￥${it.carSale}万</span>',
                        '{@/if}',
                    '{@if it.carPrice != null && it.carPrice !=0}',
                        '<span class="marginLeft-5 recommendCarPrice">指导价:${it.carPrice}万</span>',
                    '{@/if}',
                    '</div>',
                            '</div>',
                        '</a>',
                    '</li>',
                '{@/each}',
            '{@/if}',
            '{@if ImgObj === 1}',
                '{@each data.rows as it, i}',
                    '{@if i <= 5}',
                        '<li class="recommend">',
                            '{@if it.sellOut == true}',
                                '<a>',
                            '{@else}',
                                '<a href="cybapp://car/id/${it.id}">',
                            '{@/if}',
                            '<div class="recommendImgBox">',
                                '<img src="" data-src="${it.carImg}" class="recommendImg">',
                            '{@if it.sellOut == true}',
                                '<img src="img/sell_outsmall.png" class="sellOutSmall"/>',
                            '{@/if}',
                            '</div>',
                                '<div class="recommendText">',
                                    '<div class="recommendCarName strongText">${it.carName}</div>',
                                    '<div class="fontColor fontSize-14 smallOut">',
                                        '<span>外观/内饰:</span>',
                                        '<span class="marginLeft-5">${it.carFace}/${it.carInterior}</span>',
                                    '</div>',
                                    '<div class="fontColor fontSize-14 smallPrice">',
                                    '{@if it.carSale == 0}',
                                        '<span class="recommendCarSale">电议</span>',
                                    '{@else}',
                                        '<span class="recommendCarSale">￥${it.carSale}万</span>',
                                    '{@/if}',
                            '{@if it.carPrice != null && it.carPrice !=0}',
                                '<span class="marginLeft-5 recommendCarPrice">指导价:${it.carPrice}万</span>',
                            '{@/if}',
                            '</div>',
                                    '</div>',
                                '</a>',
                        '</li>',
                    '{@/if}',
                    '{@if i == 6}',
                        '<img src="./img/button_more.png" class="button_more02" id="buttonMore"/>',
                    '{@/if}',
                '{@/each}',
            '{@/if}',
        '{@/if}',
    ].join('\n');
    return HTML;
}

var sourceSecond=function(){
    var HTML=[
        '{@if OBJAPP === true}',
            '{@each data.rows as it, i}',
                '<li class="sourceFrameModuleBox">',
                    '{@if it.sellOut == true}',
                        '<a>',
                    '{@else}',
                        '<a href="cybapp://car/id/${it.id}">',
                    '{@/if}',
                    '<div class="sourceFrameImgBox">',
                    '<img src="" data-src="${it.carImg}" class="sourceFrameImg"/>',
                    '{@if it.sellOut === true}',
                        '<img src="img/sell_outsmall.png" class="sourceFrameSellOutImg"/>',
                    '{@/if}',
                    '</div>',
                    '<div class="sourceFrameCarName font-size-14 strongText ellipsisObj">${it.carName}</div>',
                    '<div class="sourceFrameCarIn ellipsisObj">外观/内饰:${it.carFace}/${it.carInterior}</div>',
                    '{@if it.carPrice != null && it.carPrice !=0}',
                        '<div class="sourceFrameCarPrice">指导价:${it.carPrice}万</div>',
                    '{@/if}',
                    '{@if it.carSale ==0}',
                        '<div class="sourceFrameCarButton">电议</div>',
                    '{@else}',
                        '<div class="sourceFrameCarButton">￥${it.carSale}万</div>',
                    '{@/if}',
                    '</a>',
                '</li>',
                '{@/each}',
            '{@/if}',
            '{@if OBJAPP === false}',
                    '{@if ImgObj === 0}',
                        '{@each data.rows as it, i}',
                            '<li class="sourceFrameModuleBox">',
                                '{@if it.sellOut == true}',
                                    '<a>',
                                '{@else}',
                                    '<a href="cybapp://car/id/${it.id}">',
                                '{@/if}',
                                '<div class="sourceFrameImgBox">',
                                '<img src="" data-src="${it.carImg}" class="sourceFrameImg"/>',
                                '{@if it.sellOut === true}',
                                    '<img src="img/sell_outsmall.png" class="sourceFrameSellOutImg"/>',
                                '{@/if}',
                                '</div>',
                                '<div class="sourceFrameCarName font-size-14 strongText ellipsisObj">${it.carName}</div>',
                                '<div class="sourceFrameCarIn ellipsisObj">外观/内饰:${it.carFace}/${it.carInterior}</div>',
                                '{@if it.carPrice != null && it.carPrice !=0}',
                                    '<div class="sourceFrameCarPrice">指导价:${it.carPrice}万</div>',
                                '{@/if}',
                                '{@if it.carSale ==0}',
                                    '<div class="sourceFrameCarButton">电议</div>',
                                '{@else}',
                                    '<div class="sourceFrameCarButton">￥${it.carSale}万</div>',
                                '{@/if}',
                                '</a>',
                            '</li>',
                        '{@/each}',
                    '{@/if}',
                    '{@if ImgObj === 1}',
                        '{@each data.rows as it, i}',
                            '{@if i <= 5}',
                                '<li class="sourceFrameModuleBox">',
                                    '{@if it.sellOut == true}',
                                        '<a>',
                                    '{@else}',
                                        '<a href="cybapp://car/id/${it.id}">',
                                    '{@/if}',
                                    '<div class="sourceFrameImgBox">',
                                    '<img src="" data-src="${it.carImg}" class="sourceFrameImg"/>',
                                    '{@if it.sellOut === true}',
                                        '<img src="img/sell_outsmall.png" class="sourceFrameSellOutImg"/>',
                                    '{@/if}',
                                    '</div>',
                                    '<div class="sourceFrameCarName font-size-14 strongText ellipsisObj">${it.carName}</div>',
                                    '<div class="sourceFrameCarIn ellipsisObj">外观/内饰:${it.carFace}/${it.carInterior}</div>',
                                    '{@if it.carPrice != null && it.carPrice !=0}',
                                        '<div class="sourceFrameCarPrice">指导价:${it.carPrice}万</div>',
                                    '{@/if}',
                                    '{@if it.carSale ==0}',
                                        '<div class="sourceFrameCarButton">电议</div>',
                                    '{@else}',
                                        '<div class="sourceFrameCarButton">￥${it.carSale}万</div>',
                                    '{@/if}',
                                    '</a>',
                                '</li>',
                            '{@/if}',
                            '{@if i == 6}',
                                '<img src="./img/button_more.png" class="button_more" id="buttonMore"/>',
                            '{@/if}',
                        '{@/each}',
                    '{@/if}',
            '{@/if}'
    ].join('\n');
    return HTML;
}

var sourceThird=function(){
    var HTML=[
        '{@if OBJAPP === true}',
            '{@each data.rows as it, i}',
                '<li class="sourceFrameRadiusBox">',
                    '{@if it.sellOut == true}',
                        '<a>',
                    '{@else}',
                        '<a href="cybapp://car/id/${it.id}">',
                    '{@/if}',
                    '<div class="sourceFrameRadiusImgBox">',
                    '<img src="" data-src="${it.carImg}" class="sourceFrameRadiusImg"/>',
                    '{@if it.sellOut === true}',
                        '<img src="img/sell_outsmall.png" class="sourceFrameRadiusSellOutImg"/>',
                    '{@/if}',
                    '</div>',
                    '<div class="sourceFrameRadiusCarName font-size-14 strongText ellipsisObj">${it.carName}</div>',
                    '<div class="sourceFrameRadiusCarIn ellipsisObj">外观/内饰:${it.carFace}/${it.carInterior}</div>',
                    '{@if it.carPrice != null && it.carPrice !=0}',
                        '<div class="sourceFrameRadiusCarPrice">指导价:${it.carPrice}万</div>',
                    '{@/if}',
                    '{@if it.carSale ==0}',
                        '<div class="sourceFrameRadiusCarButton">电议</div>',
                    '{@else}',
                        '<div class="sourceFrameRadiusCarButton">￥${it.carSale}万</div>',
                    '{@/if}',
                    '</a>',
                '</li>',
            '{@/each}',
        '{@/if}',
        '{@if OBJAPP === false}',
            '{@if ImgObj === 0}',
                '{@each data.rows as it, i}',
                    '<li class="sourceFrameRadiusBox">',
                        '{@if it.sellOut == true}',
                            '<a>',
                        '{@else}',
                            '<a href="cybapp://car/id/${it.id}">',
                        '{@/if}',
                        '<div class="sourceFrameRadiusImgBox">',
                        '<img src="" data-src="${it.carImg}" class="sourceFrameRadiusImg"/>',
                        '{@if it.sellOut === true}',
                            '<img src="img/sell_outsmall.png" class="sourceFrameRadiusSellOutImg"/>',
                        '{@/if}',
                        '</div>',
                        '<div class="sourceFrameRadiusCarName font-size-14 strongText ellipsisObj">${it.carName}</div>',
                        '<div class="sourceFrameRadiusCarIn ellipsisObj">外观/内饰:${it.carFace}/${it.carInterior}</div>',
                        '{@if it.carPrice != null && it.carPrice !=0}',
                            '<div class="sourceFrameRadiusCarPrice">指导价:${it.carPrice}万</div>',
                        '{@/if}',
                        '{@if it.carSale ==0}',
                            '<div class="sourceFrameRadiusCarButton">电议</div>',
                        '{@else}',
                            '<div class="sourceFrameRadiusCarButton">￥${it.carSale}万</div>',
                        '{@/if}',
                        '</a>',
                    '</li>',
                '{@/each}',
            '{@/if}',
            '{@if ImgObj === 1}',
                '{@each data.rows as it, i}',
                    '{@if i <= 5}',
                        '<li class="sourceFrameRadiusBox">',
                            '{@if it.sellOut == true}',
                                '<a>',
                            '{@else}',
                                '<a href="cybapp://car/id/${it.id}">',
                            '{@/if}',
                            '<div class="sourceFrameRadiusImgBox">',
                            '<img src="" data-src="${it.carImg}" class="sourceFrameRadiusImg"/>',
                            '{@if it.sellOut === true}',
                                '<img src="img/sell_outsmall.png" class="sourceFrameRadiusSellOutImg"/>',
                            '{@/if}',
                            '</div>',
                            '<div class="sourceFrameRadiusCarName font-size-14 strongText ellipsisObj">${it.carName}</div>',
                            '<div class="sourceFrameRadiusCarIn ellipsisObj">外观/内饰:${it.carFace}/${it.carInterior}</div>',
                            '{@if it.carPrice != null && it.carPrice !=0}',
                                '<div class="sourceFrameRadiusCarPrice">指导价:${it.carPrice}万</div>',
                            '{@/if}',
                            '{@if it.carSale ==0}',
                                '<div class="sourceFrameRadiusCarButton">电议</div>',
                            '{@else}',
                                '<div class="sourceFrameRadiusCarButton">￥${it.carSale}万</div>',
                            '{@/if}',
                            '</a>',
                        '</li>',
                    '{@/if}',
                    '{@if i == 6}',
                        '<img src="./img/button_more.png" class="button_more" id="buttonMore"/>',
                    '{@/if}',
                '{@/each}',
            '{@/if}',
        '{@/if}',
    ].join('\n');
    return HTML;
}

var sourceFourth=function(){
    var HTML=[
        '{@if OBJAPP === true}',
            '{@each data.rows as it, i}',
                '<li class="recommendNoFrame">',
                '{@if it.sellOut == true}',
                    '<a>',
                '{@else}',
                    '<a href="cybapp://car/id/${it.id}">',
                '{@/if}',
                '<div class="recommendNoFrameImgBox">',
                    '<img src="" data-src="${it.carImg}" class="recommendNoFrameImg">',
                '{@if it.sellOut == true}',
                    '<img src="img/sell_outsmall.png" class="NoFrameSellOutSmall"/>',
                '{@/if}',
                '</div>',
                    '<div class="recommendNoFrameText">',
                        '<div class="recommendNoFrameCarName strongText">${it.carName}</div>',
                        '<div class="fontColor NoFrameSmallOut">',
                            '<span>外观/内饰:</span>',
                            '<span class="marginLeft-5">${it.carFace}/${it.carInterior}</span>',
                        '</div>',
                        '<div class="fontColor fontSize-14 NoFramesmallPrice">',
                    '{@if it.carSale ==0}',
                        '<span class="recommendNoFrameCarSale">电议</span>',
                    '{@else}',
                        '<span class="recommendNoFrameCarSale">￥${it.carSale}万</span>',
                    '{@/if}',
                '{@if it.carPrice != null && it.carPrice !=0}',
                    '<span class="marginLeft-5 recommendNoFrameCarPrice">指导价:${it.carPrice}万</span>',
                '{@/if}',
                '</div>',
                        '</div>',
                    '</a>',
                '</li>',
            '{@/each}',
        '{@/if}',
        '{@if OBJAPP === false}',
            '{@if ImgObj === 0}',
                '{@each data.rows as it, i}',
                    '<li class="recommendNoFrame">',
                    '{@if it.sellOut == true}',
                        '<a>',
                    '{@else}',
                        '<a href="cybapp://car/id/${it.id}">',
                    '{@/if}',
                    '<div class="recommendNoFrameImgBox">',
                        '<img src="" data-src="${it.carImg}" class="recommendNoFrameImg">',
                    '{@if it.sellOut == true}',
                        '<img src="img/sell_outsmall.png" class="NoFrameSellOutSmall"/>',
                    '{@/if}',
                    '</div>',
                        '<div class="recommendNoFrameText">',
                            '<div class="recommendNoFrameCarName strongText">${it.carName}</div>',
                            '<div class="fontColor NoFrameSmallOut">',
                                '<span>外观/内饰:</span>',
                                '<span class="marginLeft-5">${it.carFace}/${it.carInterior}</span>',
                            '</div>',
                            '<div class="fontColor fontSize-14 NoFramesmallPrice">',
                    '{@if it.carSale ==0}',
                        '<span class="recommendNoFrameCarSale">电议</span>',
                    '{@else}',
                        '<span class="recommendNoFrameCarSale">￥${it.carSale}万</span>',
                    '{@/if}',
                    '{@if it.carPrice != null && it.carPrice !=0}',
                        '<span class="marginLeft-5 recommendNoFrameCarPrice">指导价:${it.carPrice}万</span>',
                    '{@/if}',
                    '</div>',
                            '</div>',
                        '</a>',
                    '</li>',
                '{@/each}',
            '{@/if}',
            '{@if ImgObj === 1}',
                '{@each data.rows as it, i}',
                    '{@if i <= 5}',
                        '<li class="recommendNoFrame">',
                            '{@if it.sellOut == true}',
                                '<a>',
                            '{@else}',
                                '<a href="cybapp://car/id/${it.id}">',
                            '{@/if}',
                            '<div class="recommendNoFrameImgBox">',
                                '<img src="" data-src="${it.carImg}" class="recommendNoFrameImg">',
                            '{@if it.sellOut == true}',
                                '<img src="img/sell_outsmall.png" class="NoFrameSellOutSmall"/>',
                            '{@/if}',
                            '</div>',
                                '<div class="recommendNoFrameText">',
                                    '<div class="recommendNoFrameCarName strongText">${it.carName}</div>',
                                    '<div class="fontColor NoFrameSmallOut">',
                                        '<span>外观/内饰:</span>',
                                        '<span class="marginLeft-5">${it.carFace}/${it.carInterior}</span>',
                                    '</div>',
                                    '<div class="fontColor fontSize-14 NoFramesmallPrice">',
                                        '{@if it.carSale ==0}',
                                            '<span class="recommendNoFrameCarSale">电议</span>',
                                        '{@else}',
                                            '<span class="recommendNoFrameCarSale">￥${it.carSale}万</span>',
                                        '{@/if}',
                            '{@if it.carPrice != null && it.carPrice !=0}',
                                '<span class="marginLeft-5 recommendNoFrameCarPrice">指导价:${it.carPrice}万</span>',
                            '{@/if}',
                            '</div>',
                                    '</div>',
                                '</a>',
                        '</li>',
                    '{@/if}',
                    '{@if i == 6}',
                        '<img src="./img/button_more.png" class="button_more03" id="buttonMore"/>',
                    '{@/if}',
                '{@/each}',
            '{@/if}',
        '{@/if}'
    ].join('\n');
    return HTML;
}

